image_size: 256
num_channels: 256
num_res_blocks: 2
channel_mult: "1,1,2,2,4,4" # check
learn_sigma: True
class_cond: False
attention_resolutions: "32,16,8"
num_heads: 4
num_head_channels: -1 # check
num_heads_upsample: -1
dropout: 0.0
use_checkpoint: False
use_scale_shift_norm: True
resblock_updown: False
use_fp16: False
use_new_attention_order: False
model_path: models/div2k256_v1.pt
